export const AUTHORIZATION_ADMIN = 'AUTHORIZATION_ADMIN'
export const UPDATE_CLIENT_LIST = 'UPDATE_CLIENT_LIST'


export const UPDATE_ACTIVE_PAGE = 'UPDATE_ACTIVE_PAGE'
export const GET_SINGLE_CLIENT  = 'GET_SINGLE_CLIENT'
export const EDITING_CLIENT = 'EDITING_CLIENT'