export const AUTHORIZATION_ADMIN = 'AUTHORIZATION_ADMIN'
export const UPDATE_CLIENT_LIST = 'UPDATE_CLIENT_LIST'


export const UPDATE_ACTIVE_PAGE = 'UPDATE_ACTIVE_PAGE'
export const GET_SINGLE_CLIENT  = 'GET_SINGLE_CLIENT'
export const EDITING_CLIENT = 'EDITING_CLIENT'

export const UPDATE_PRODUCT_LIST = 'UPDATE_PRODUCT_LIST'
export const GET_SINGLE_PRODUCT  = 'GET_SINGLE_PRODUCT'
export const EDITING_PRODUCT = 'EDITING_PRODUCT'

